/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.discord4j:discord4j-core:3.2.2")
    implementation("org.mongodb:mongodb-driver-sync:4.5.0")
    implementation("com.fasterxml.jackson.core:jackson-core:2.13.1")
    implementation("ch.qos.logback:logback-classic:1.2.10")
}

group = "me.gacha"
version = "1.0"
description = "Gacha"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17
application.mainClass.set("me.gacha.gacha.Core")

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}